### ISSUE TITLE
Fails to build with Jessie's 3.16

### ISSUE THREAD

**Issue by f00b4r0** [dtaht/sch_cake#91]
Hi,

Current cobalt fails to build on Debian Jessie's 3.16:

```
$ make
make -C /lib/modules/3.16.0-5-586/build SUBDIRS=/usr/src/sch_cake.orig modules LDFLAGS_MODULE="--build-id=0x115af5dcec46f82180fcea7adac2fe743bad98d9" CFLAGS_MODULE="-DCAKE_VERSION=\\\"115af5dcec46f82180fcea7adac2fe743bad98d9\\\""
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-5-586'
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-5-586'
  CC [M]  /usr/src/sch_cake.orig/sch_cake.o
In file included from /usr/src/sch_cake.orig/sch_cake.c:76:0:
/usr/src/sch_cake.orig/cobalt.h:162:27: warning: "__is_defined" is not defined [-Wundef]
     (IS_MODULE(option) && __is_defined(MODULE)))
                           ^
/usr/src/sch_cake.orig/sch_cake.c:78:5: note: in expansion of macro ‘IS_REACHABLE’
 #if IS_REACHABLE(CONFIG_NF_CONNTRACK)
     ^
/usr/src/sch_cake.orig/cobalt.h:162:39: error: missing binary operator before token "("
     (IS_MODULE(option) && __is_defined(MODULE)))
                                       ^
/usr/src/sch_cake.orig/sch_cake.c:78:5: note: in expansion of macro ‘IS_REACHABLE’
 #if IS_REACHABLE(CONFIG_NF_CONNTRACK)
     ^
/usr/src/sch_cake.orig/cobalt.h:162:27: warning: "__is_defined" is not defined [-Wundef]
     (IS_MODULE(option) && __is_defined(MODULE)))
                           ^
/usr/src/sch_cake.orig/sch_cake.c:528:5: note: in expansion of macro ‘IS_REACHABLE’
 #if IS_REACHABLE(CONFIG_NF_CONNTRACK)
     ^
/usr/src/sch_cake.orig/cobalt.h:162:39: error: missing binary operator before token "("
     (IS_MODULE(option) && __is_defined(MODULE)))
                                       ^
/usr/src/sch_cake.orig/sch_cake.c:528:5: note: in expansion of macro ‘IS_REACHABLE’
 #if IS_REACHABLE(CONFIG_NF_CONNTRACK)
     ^
/usr/src/sch_cake.orig/sch_cake.c: In function ‘cake_get_tcphdr’:
/usr/src/sch_cake.orig/sch_cake.c:925:7: error: implicit declaration of function ‘__tcp_hdrlen’ [-Werror=implicit-function-declaration]
       min(__tcp_hdrlen(tcph), bufsize), buf);
       ^
In file included from /usr/src/linux-headers-3.16.0-5-common/arch/x86/include/asm/percpu.h:44:0,
                 from /usr/src/linux-headers-3.16.0-5-common/arch/x86/include/asm/preempt.h:5,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/preempt.h:18,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/spinlock.h:50,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/seqlock.h:35,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/time.h:5,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/stat.h:18,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/module.h:10,
                 from /usr/src/sch_cake.orig/sch_cake.c:53:
/usr/src/linux-headers-3.16.0-5-common/include/linux/kernel.h:716:17: warning: comparison of distinct pointer types lacks a cast [enabled by default]
  (void) (&_min1 == &_min2);  \
                 ^
/usr/src/sch_cake.orig/sch_cake.c:925:7: note: in expansion of macro ‘min’
       min(__tcp_hdrlen(tcph), bufsize), buf);
       ^
/usr/src/sch_cake.orig/sch_cake.c: In function ‘cake_ack_filter’:
/usr/src/sch_cake.orig/sch_cake.c:1026:1: error: ‘n’ undeclared (first use in this function)
 n
 ^
/usr/src/sch_cake.orig/sch_cake.c:1026:1: note: each undeclared identifier is reported only once for each function it appears in
/usr/src/sch_cake.orig/sch_cake.c:1039:3: error: expected ‘;’ before ‘if’
   if (((tcp_flag_word(tcph_check) &
   ^
/usr/src/sch_cake.orig/sch_cake.c: In function ‘cake_drop’:
/usr/src/sch_cake.orig/sch_cake.c:1318:2: error: implicit declaration of function ‘qdisc_tree_decrease_qlen’ [-Werror=implicit-function-declaration]
  qdisc_tree_reduce_backlog(sch, 1, len);
  ^
/usr/src/sch_cake.orig/sch_cake.c: In function ‘cake_enqueue’:
/usr/src/sch_cake.orig/sch_cake.c:1429:5: error: implicit declaration of function ‘codel_watchdog_schedule_ns’ [-Werror=implicit-function-declaration]
     codel_watchdog_schedule_ns(&q->watchdog, next, true);
     ^
/usr/src/sch_cake.orig/sch_cake.c: In function ‘cake_dump_stats’:
/usr/src/sch_cake.orig/sch_cake.c:2573:3: error: implicit declaration of function ‘nla_put_u64_64bit’ [-Werror=implicit-function-declaration]
   PUT_TSTAT_U64(SENT_BYTES64, b->bytes);
   ^
cc1: some warnings being treated as errors
/usr/src/linux-headers-3.16.0-5-common/scripts/Makefile.build:268: recipe for target '/usr/src/sch_cake.orig/sch_cake.o' failed
make[4]: *** [/usr/src/sch_cake.orig/sch_cake.o] Error 1
/usr/src/linux-headers-3.16.0-5-common/Makefile:1355: recipe for target '_module_/usr/src/sch_cake.orig' failed
make[3]: *** [_module_/usr/src/sch_cake.orig] Error 2
Makefile:181: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-5-586'
Makefile:8: recipe for target 'default' failed
make: *** [default] Error 2
```

Hope that helps

**Comment by f00b4r0** [comment]
Tried with #85 applied:

```
$ make
make -C /lib/modules/3.16.0-5-586/build SUBDIRS=/usr/src/sch_cake.orig modules LDFLAGS_MODULE="--build-id=0x115af5dcec46f82180fcea7adac2fe743bad98d9" CFLAGS_MODULE="-DCAKE_VERSION=\\\"115af5dcec46f82180fcea7adac2fe743bad98d9\\\""
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-5-586'
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-5-586'
  CC [M]  /usr/src/sch_cake.orig/sch_cake.o
/usr/src/sch_cake.orig/sch_cake.c: In function ‘cake_get_tcphdr’:
/usr/src/sch_cake.orig/sch_cake.c:925:7: error: implicit declaration of function ‘__tcp_hdrlen’ [-Werror=implicit-function-declaration]
       min(__tcp_hdrlen(tcph), bufsize), buf);
       ^
In file included from /usr/src/linux-headers-3.16.0-5-common/arch/x86/include/asm/percpu.h:44:0,
                 from /usr/src/linux-headers-3.16.0-5-common/arch/x86/include/asm/preempt.h:5,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/preempt.h:18,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/spinlock.h:50,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/seqlock.h:35,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/time.h:5,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/stat.h:18,
                 from /usr/src/linux-headers-3.16.0-5-common/include/linux/module.h:10,
                 from /usr/src/sch_cake.orig/sch_cake.c:53:
/usr/src/linux-headers-3.16.0-5-common/include/linux/kernel.h:716:17: warning: comparison of distinct pointer types lacks a cast [enabled by default]
  (void) (&_min1 == &_min2);  \
                 ^
/usr/src/sch_cake.orig/sch_cake.c:925:7: note: in expansion of macro ‘min’
       min(__tcp_hdrlen(tcph), bufsize), buf);
       ^
/usr/src/sch_cake.orig/sch_cake.c: In function ‘cake_ack_filter’:
/usr/src/sch_cake.orig/sch_cake.c:1026:1: error: ‘n’ undeclared (first use in this function)
 n
 ^
/usr/src/sch_cake.orig/sch_cake.c:1026:1: note: each undeclared identifier is reported only once for each function it appears in
/usr/src/sch_cake.orig/sch_cake.c:1039:3: error: expected ‘;’ before ‘if’
   if (((tcp_flag_word(tcph_check) &
   ^
/usr/src/sch_cake.orig/sch_cake.c: In function ‘cake_drop’:
/usr/src/sch_cake.orig/sch_cake.c:1318:2: error: implicit declaration of function ‘qdisc_tree_decrease_qlen’ [-Werror=implicit-function-declaration]
  qdisc_tree_reduce_backlog(sch, 1, len);
  ^
/usr/src/sch_cake.orig/sch_cake.c: In function ‘cake_enqueue’:
/usr/src/sch_cake.orig/sch_cake.c:1429:5: error: implicit declaration of function ‘codel_watchdog_schedule_ns’ [-Werror=implicit-function-declaration]
     codel_watchdog_schedule_ns(&q->watchdog, next, true);
     ^
cc1: some warnings being treated as errors
/usr/src/linux-headers-3.16.0-5-common/scripts/Makefile.build:268: recipe for target '/usr/src/sch_cake.orig/sch_cake.o' failed
make[4]: *** [/usr/src/sch_cake.orig/sch_cake.o] Error 1
/usr/src/linux-headers-3.16.0-5-common/Makefile:1355: recipe for target '_module_/usr/src/sch_cake.orig' failed
make[3]: *** [_module_/usr/src/sch_cake.orig] Error 2
Makefile:181: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-5-586'
Makefile:8: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by tohojo** [comment]
Assuming this is fixed by Kevin's latest compat fixes; otherwise, please reopen :)
