### ISSUE TITLE
Cant compile on 4.5.4

### ISSUE THREAD

**Issue by zcecc22** [dtaht/sch_cake#23]
Hi everyone,

Im getting the following during make:

make -C /lib/modules/4.5.4ll/build SUBDIRS=/array0/zcecc22/projects/sch_cake modules LDFLAGS_MODULE="--build-id=0x4471e48a55ac41e1caaeab74ed3278fa1d461e4a" CFLAGS_MODULE="-DCAKE_VERSION=\\"4471e48a55ac41e1caaeab74ed3278fa1d461e4a\\""
make[1]: Entering directory '/array0/zcecc22/projects/linux-4.5.4'
  CC [M]  /array0/zcecc22/projects/sch_cake/sch_cake.o
/array0/zcecc22/projects/sch_cake/sch_cake.c: In function ‘cake_enqueue’:
/array0/zcecc22/projects/sch_cake/sch_cake.c:728:3: error: implicit declaration of function ‘qdisc_tree_reduce_backlog’ [-Werror=implicit-function-declaration]
   qdisc_tree_reduce_backlog(sch, 1, len);
   ^
cc1: some warnings being treated as errors

**Comment by chromi** [comment]
> On 21 May, 2016, at 16:17, Vincent Frentzel notifications@github.com wrote:
> 
> Hi everyone,
> 
> Im getting the following during make:
> 
> make -C /lib/modules/4.5.4ll/build SUBDIRS=/array0/zcecc22/projects/sch_cake modules LDFLAGS_MODULE="--build-id=0x4471e48a55ac41e1caaeab74ed3278fa1d461e4a" CFLAGS_MODULE="-DCAKE_VERSION=\"4471e48a55ac41e1caaeab74ed3278fa1d461e4a\""
> make[1]: Entering directory '/array0/zcecc22/projects/linux-4.5.4'
> CC [M] /array0/zcecc22/projects/sch_cake/sch_cake.o
> /array0/zcecc22/projects/sch_cake/sch_cake.c: In function ‘cake_enqueue’:
> /array0/zcecc22/projects/sch_cake/sch_cake.c:728:3: error: implicit declaration of function ‘qdisc_tree_reduce_backlog’ [-Werror=implicit-function-declaration]
> qdisc_tree_reduce_backlog(sch, 1, len);
> ^
> cc1: some warnings being treated as errors

This is a side-effect of an internal kernel API change being backported to two supposedly stable branches - a policy which I strongly disagree with.

I have, however, just updated the kernel version check to cover your case.  Alternatively, you could use a later version of the kernel.
- Jonathan Morton
